imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    locale: en
    project.name: WebHome
    app.code: APP

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        project_name: "%project.name%"
        app_name: null
        app_icon: null

hwi_oauth:
#    http_client:
#        timeout: 10
    firewall_names: [secured_area]
    resource_owners:
        webhome:
            type: oauth2
            client_id:           %client_id%
            client_secret:       %client_secret%
            authorization_url:   %webhome_auth_url%/oauth/v2/auth
            access_token_url:    %webhome_auth_url%/oauth/v2/token
            infos_url:           %webhome_auth_url%/api/user
            scope:               "read"
            user_response_class: Ndewez\WebHome\CommonBundle\Response\OAuthWebHomeUserResponse
            paths:
                identifier: id
                nickname:   username
                realname:   ["first_name", "last_name"]
                firstname:  first_name
                lastname:   last_name
                locale:     locale
                roles:      group.authorizations
